packages:
  - 'packages/*'

catalog:
  '@antfu/eslint-config': 6.2.0
  '@types/node': 24.10.1
  '@vitest/coverage-v8': 4.1.10
  '@vitest/ui': 4.1.10
  cloudevents: 10.0.0
  eslint: 9.39.1
  mongodb: 7.0.0
  mongodb-memory-server: 10.2.0
  typescript: 5.9.2
  vite: 8.1.5
  vite-plugin-dts: 5.0.3
  vitest: 4.1.10
