packages:
  - 'packages/*'

catalog:
  '@antfu/eslint-config': 6.2.0
  '@types/node': 24.10.1
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  cloudevents: 10.0.0
  eslint: 9.39.1
  mongodb: 6.18.0
  mongodb-memory-server: 10.2.0
  typescript: 5.9.2
  vite: 7.2.4
  vite-plugin-dts: 4.5.4
  vitest: 3.2.4
